const LOAD_DATA = "LOADDATA";
const SUCCESS_DATA = "SUCCESS";
const ERROR_DATA = "ERROR";
const SUCCESS_LIST = "SUCCESSLIST";
const LOAD_LIST = "LOADDATA";
const ERROR_LIST = "ERRORLIST";
const INV_LOADING = "INVLOADING"
const INV_DATA = "INVDATA";
const INV_ERROR = "INVERROR";


export{LOAD_DATA,SUCCESS_DATA,ERROR_DATA,SUCCESS_LIST,LOAD_LIST,ERROR_LIST,INV_LOADING,INV_DATA,INV_ERROR };